### ISSUE TITLE
Support for elasticsearch > 8.3 ?

### ISSUE THREAD

**Issue by joao-mil** [ClearcodeHQ/pytest-elasticsearch#416]
I would like to use pytest-elasticsearch to test code for elasticsearch 8.3 and I see that there's a MR open for it but the pipelines are failing.

Any idea when this will work?

If nobody is actively maintaining it anymore, could you give some pointers on how to fix it?

**Comment by fizyk** [comment]
@joao-mil I do maintain it, kind of. The code in PR  #384 works/worked at the time when being run on local machine. However I wasn't able to run it on github-actions. Elasticsearch 8 and above requires an increased amount of RAM to run, and somehow I wasn't able to properly limit it's RAM usage and run on github-actions, at least I think that's the root cause.

If you'd be able to look at this PR, and if you have time to tinker and fix whatever is wrong with CI, I'd gladly accept your help.

**Comment by joao-mil** [comment]
Thanks a lot! I will try to take a look at it in the comming weeks.
